### ISSUE TITLE
Tombs of Amascut update checklist

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#15478]
[August 24th](https://twitter.com/OldSchoolRS/status/1550472341435588608) will bring with it the new raid Tombs of Amascut, and with that new content we'll need to make a number of updates to the client to accommodate it. This issue is to be used to track any expected or known features and bugs related to this update.

- [x] Tombs of Amascut regions (and its surrounding regions) should be added to the Discord plugin to display accurate rich presence status (c1d98ebff7c72ac93139bd01eb79a1c5ef028d9f)
- [x] ~~Tombs of Amascut regions may need to be added to the Skybox plugin if a non-black skybox would be appropriate for them~~ (seems to be fine with no changes)
- [x] The dungeon icon for the raid on the world map, and any other added icons, should get the usual World Map plugin treatment with their corresponding names (fd932639f696316f4e17f31f6fd3852a5f390c7f)
- [x] Depending on the implementation of the [Lightbearer](https://oldschool.runescape.wiki/w/Lightbearer), the special attack regeneration indicator of the Regen Meters plugin may need to be updated to continue working correctly (15ca8132a0f8f166f75c928b23d2797749c74f60)
- [x] Any untradeable rewards (or variants of rewards, eg. [Elidinis' ward](https://oldschool.runescape.wiki/w/Elidinis%27_ward)) should have their tradeable variants added to the ItemMapping enum so their prices are accurately shown in the bank and other interfaces (53c4bfedcce7acc3903cf2407a0f45a8d90fbe4d)
- [x] [Stat renewal potions](https://oldschool.runescape.wiki/w/Stat_renewal) will need to be added to the Skill Calculator plugin, and have the restore effect added to the Item Stats plugin and Timers plugin (d083f63f1b07f5711e4d11a35dda06cae5b5365f and 597aa299a5d1dc434b3f6524df43678ace59de32)
  - [x] timers plugin implementation is pending after release
- [x] The Tombs of Amascut login screen background should be added to the Login Screen plugin (#15573)
- [x] ~~Bosses with transformations may need to be handled via NpcUtil to avoid becoming uninteractable via Menu Entry Swapper/Entity Hider plugins~~ (appears to work fine with no changes)
- [x] Our code for showing runes stored in the rune pouch via the Rune Pouch plugin will need to be updated to accommodate a 4th rune slot. A possible design for a 4-rune pouch would be to remove the digits next to the stored runes and show the icons in a 2x2 grid. (exact numbers of each rune can still be seen in the tooltip when hovering the rune pouch) Furthermore, if the new rune pouch uses a separate item ID, that new ID will need to be added to any various plugins which check for its presence in a player's inventory. (8c26ac566dbfeb0a185da6768394d7e2fba6bed2)
  - [x] needs item ID update on day of release (00b510f6d054565ef55ff10cbed243df481f5d83 and 5ec7ad443d8f4664ffc675a3ad4829e9d257c38a)
- [x] Hiscores will be updated to add the raid (possibly also easy and/or hard mode), requiring changes to the HTTP API and Hiscores plugin (d86bd8bd6ac1d3ce7e166066d6bde917d3a7da4f)
  - [x] needs mapping.json update on day of release (b888dca43595fbbf12ac1e9587062ca1ea5b5247)
- [x] The raid will have kill count and completion time messages, which should be picked up and stored by the Chat Commands plugin (72c3067758ce6b64ad0475eb30e604a4fc0a2d9e)
- [x] The pet(s) offered from the raid must also be picked up by the Chat Commands plugin (09866b308d688bfe98690b3c9bdc39f201ba03c0)
- [x] Loot collected from the raid should be picked up by the Loot Tracker plugin (possibly indicating the tier of difficulty, since the rates are not equal between the raid "tiers") (45b6a0d0378f52928b1df09acc6d8c4aa745746c)
- [x] Some bosses have model face counts in excess of what the GPU plugin currently renders, so that will need to be bumped up to handle rendering them. (8a287305f1b15b29e075fac7cc5c21626b97652d)
- [x] Chat commands: `!kc toa entry`, `!kc toa expert`, `!kc toa`
- [x] ToA party and raid UIs should be added as widget overlays to avoid overlapping of game UI and our overlays (6f63611b3e84a7d5e7a327368cbb7fbb1f3ab2b5)
- [x] [ToA consumables](https://oldschool.runescape.wiki/w/Tombs_of_Amascut#Consumables) (honey locust, ambrosia, etc.) should be added to item stats, item identification, item charges plugins (efe2012dfa3c66cfb7bb2a680e682407f35f730c)
- [x] [Cache of runes](https://oldschool.runescape.wiki/w/Cache_of_runes) should be supported by the Loot Tracker plugin
- [x] TOA chest loot should be added to the screenshot plugin

**Comment by Adam-** [comment]
The rune pouch changes have been added, but will require setting `NUM_SLOTS=4` as well as adding the new item ids for the new pouch(s)

**Comment by Nightfirecat** [comment]
All items on this list are implemented or closed without any changes needed, so this issue is completed. :tada:
