### ISSUE TITLE
Secrets of the North Update checklist

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#16133]
- [x] **Boss Timers plugin:** Phantom Muspah respawn timer (~~#16155~~ 8f7888f3f9)
- [ ] **Agilty plugin:** Weiss broken fence shortcut highlight (deferred to #16159)
- [x] **Item Stats plugin:** Saturated heart item stats (1f3dc741bcba0bb18d7788c31681688132c46c65)
- [x] **Item Stats plugin:** Forgotten brews item stats (751243c4c2816b8e8bbf243535d967a992d8a33c)
- [x] ~~**ItemMapping.java:** Item mapping of Saturated heart -> Imbued heart~~ (saturated heart is becoming tradeable with next week's update)
- [x] **Clue Scrolls plugin:** Add Ancient sceptre as alternative to Ancient staff for negative prayer clue step (#16143)
- [x] **Interface styles:** HD healthbar for Phantom Muspah's shield (#16146)
- [x] **Loot Tracker:** Frozen cache loot tracking (#16154)

**Comment by ragnarokatz** [comment]
@Nightfirecat Hello, I would like to work on the following two items:
- Agilty plugin: Weiss broken fence shortcut highlight
- Clue Scrolls plugin: Add Ancient sceptre as alternative to Ancient staff for negative prayer clue step

However, for the agility plugin, I'm not sure how to find the obstacle IDs listed in file `runelite-client/src/main/java/net.runelite.client/game/AgilityShortcut`, such as `LITTLE_BOULDER` or `BROKEN_FENCE_2618`.

**Comment by Nightfirecat** [comment]
You should [use the client developer tools](https://github.com/runelite/runelite/wiki/Using-the-client-developer-tools) to identify the object id ingame

**Comment by ragnarokatz** [comment]
@Nightfirecat Thank you. I'll give it a try.

**Comment by ragnarokatz** [comment]
after an afternoon's hacking, item
- Agilty plugin: Weiss broken fence shortcut highlight
proves to be more than a handful. The broken fence turns out to be a multiloc object, and the agility plugin's support for multiloc object seems to be limited for the time being.

I am no longer working on this issue and whoever wants to give it a shot, please feel free to take it up.

**Comment by Enriath** [comment]
Another thing that needs doing: HD healthbar for the Phantom Muspah's shield

**Comment by Enriath** [comment]
The loot tracker should maybe support opening Frozen Caches as well?

**Comment by Nightfirecat** [comment]
All of these items have been completed, thanks all for the help!
