### ISSUE TITLE
Desert Treasure II - The Fallen Empire update checklist

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#16819]
### Type

Other

### Operating System

None

### To do:
- [ ] **Boss Timers plugin:** Add respawn timers for the new bosses
- [ ] **Chat Commands plugin:** Add `!kc` shortnames for new bosses
- [ ] **Clues plugin:** Add the [Ring of shadows](https://oldschool.runescape.wiki/w/Ring_of_shadows) as an alternative to the Ring of visibility in any clues where it's needed
- [ ] **Discord plugin:** Add or update regions involved with the quest and bosses
- [ ] **Hiscores plugin:** Add icons for the new bosses
- [x] **Quests API file:** Add The Fallen Empire entry (cca72dec9f4a585b0f1cbd01f4e7b8ce3ff6a1ca)
- [ ] **Regeneration Meter:** Update to work with the unique "special attack" mechanic of the [Soulreaper axe](https://oldschool.runescape.wiki/w/Soulreaper_axe)
- [ ] **Skybox plugin:** Add colors for new regions as needed
- [ ] **Slayer plugin:** Add icons for boss tasks
- [ ] **World Map plugin:** Add quest start point

### To check and implement if applicable:
- [ ] **Chat Commands plugin:** Confirm that kill count and personal best times are tracked properly for the new bosses
- [ ] **ItemMapping:** Add blood torva -> normal torva mapping (if it passes the poll)
- [ ] **Loot Tracker plugin:** Support new boss loot tracking (if it doesn't already work)
- [ ] **NPCUtil:** Add isDying support for new bosses (if it doesn't already work)
- [ ] **World Map plugin:** Add tooltips to any other newly-added icons (dungeons, etc.)

### RuneLite version

.

**Comment by goldcodeo** [comment]
Do we need to wait for the game update to start working on there, or are some of the possible, now ?

**Comment by Nightfirecat** [comment]
There isn't really anything that's possible in advance. At minimum, most items require the associated NpcID/ItemID entries to be added to runelite-api, or knowing the IDs of regions ingame. Those won't be added until day of release.

**Comment by Whiteaj36** [comment]
Can confirm that Sanguine Torva is needed to add to the mapping, or at least needs its own item entry into ItemID.java. If there's an easy way to get the item ID i can post a PR up. But not sure how to get that item ID.

**Comment by geheur** [comment]
There are item ids in ItemID.java

**Comment by Birger9** [comment]
Hi! I'm doing an open source course in University where we have to contribute to an open source project. I would love to contribute to Runelite so I'm wondering if the following tasks are still available: Item Stats plugin, Timers plugin, world map plugin, Skybox plugin and Regeneration Meter plugin? @Nightfirecat 

I would like to do start with the Timers plugin task if possible. And do the rest after that. So would love to be assignes to this issue and do the remaining tasks

**Comment by Nightfirecat** [comment]
The remaining items haven't been worked on by anyone else in any capacity that I'm aware of, so we'd be happy to accept contributions that would take care of them.

**Comment by Birger9** [comment]
Okey great! Then I will start working on these tasks the coming weeks and I will go through the codebase and your contribution docs :) Can you assign me this issue?

**Comment by Nightfirecat** [comment]
I can't, issues can only be assigned to repo team members

**Comment by OmbudRov** [comment]
can i work on adding soulreaper axe to the regen meter plugin if anyone else isnt working on it already?

**Comment by OmbudRov** [comment]
ahhh didnt know he they meant it for all of them

**Comment by Nightfirecat** [comment]
Sure. We don't really have a system to "reserve" open issues/items, so go ahead

**Comment by GxH033** [comment]
Vardorvis boss timer pls
