### ISSUE TITLE
Varlamore meta issue

### ISSUE THREAD

**Issue by Adam-** [runelite/runelite#17586]
- [x] new farming patches (14b058400787847103e744c925af7a260a79649f)
- [x] new fairy rings: ajp (#17587)
- [x] new clues (#17590)
- [x] gpu hillskew textures are broken (cdfc401ab6df5d2f97c84f86a896fa1394626133)
- [x] roof removal at hunters guild and bazaar is broken f5c04bf327ea7c72ac155d2e3342884670e23f69
- [x] new hiscores (f533dc70182a2e71c7b641fa25dfd8388d287a2a)
- [x] loottracker (#17593)
    - [x] lunar chest
    - [x] fortis colosseum
    - [x] loot sacks
- [x] new login screen (#17605)
- [x] new "doom" hitsplat type (#17620)
- [x] item stats for new consumables (#17607)
- [x] weapon categories changed? attack style plugin is broken? ffe16454ba894d673db91e2d1fd8d3c4c265b2c7
- [x] several new hunter traps (#17604)
- [x] discord plugin regions (6b793fc0e5095c7f63eeeda4ae091d691e23c7b3)

**Comment by Adam-** [comment]
```
{{Clue info
|id = 967
|text = The cryptic reveals where to search:<br><br>Search the bookshelf with a skull on it inside the Burrow.
|notes = Search the bookshelf near in the Hunter Guild.
|map = {{Map|1569,9460|mtype=pin|plane=0|mapID=-1}}
}
```

```
{{Clue info
|id = 972
|text = The emote reveals <br><br>Yawn in the Fortis Grand Museum.<br>Equip an emerald necklace, blue skirt, and turqoise gnome robe top.
|items = Equip an emerald necklace, blue skirt, and turqoise gnome robe top.
|notes = Perform the [[yawn]] emote near inside the Fortis Grand Museum
|map = {{Map|1712,3163|mtype=pin|plane=0|mapID=-1}}
```

```
{{Clue info
|id = 969
|text = The coordinate reveals where to dig:<br><br>0.42N 27.35W
|notes = Dig north of Ortus Farm
The clue has an additional challenge:

Kill an [[Armadylean guard]].
|map = {{Map|1557,3183|mtype=pin|plane=0|mapID=-1}}
}}
```

```
{{Clue info
|id = 365
|text = The emote reveals <br><br>Bow within the temple in Civitas illa Fortis.<br>Equip the full set of Sunfire Fanatic armour.
|items = Equip the full set of Sunfire Fanatic armour.
|notes = Perform the [[bow]] emote near inside the temple in Civitas illa Fortis
|map = {{Map|1699,3087|mtype=pin|plane=0|mapID=-1}}
}}
```

```
{{Clue info
|id = 971
|text = The cryptic reveals who to speak to:<br><br>With drinks and dwarves I make my way, upon my head a glass will stay.
|notes = Speak to [[Funbo]] inside Cam Torum's pub.
|map = {{Map|1432,9584|mtype=pin|plane=1|mapID=-1}}
}}
```

```
{{Clue info
|id = 963
|text = The cryptic reveals where to dig:<br><br>A J P 3 0 1 5
|notes = Dig near [[fairy ring]] {{Fairycode|AJP}}
|map = {{Map|1646,3012|mtype=pin|plane=0|mapID=-1}}
}}
```

```
{{Clue info
|id = 965
|text = The cipher reveals who to speak to:<br><br>BXJA UNJMNA YRCAR
|notes = Speak to [[Soar Leader Pitri]] at the top of the Hunter Guild.
The clue has an additional challenge:

A puzzle box.undefined
|map = {{Map|1558,3046|mtype=pin|plane=2|mapID=-1}}
}}
```

```
{{Clue info
|id = 964
|text = The clue reveals who to speak to:<br><br>I'd like to hear some music.
Come and see me on the bridge in
Falador Park, and play:
The Moons of Ruin
Thanks,
Cecilia
|notes = Speak to [[Cecilia]] on the bridge in Falador Park. Play the [[music]] track [[The Moons of Ruin]].
|map = {{Map|2990,3384|mtype=pin|plane=0|mapID=-1}}
}}
```

```
{{Clue info
|id = 970
|text = The coordinate reveals where to dig:<br><br>1.33S 24.24W
|notes = Dig west of the Bazaar in Civitas illa Fortis
|map = {{Map|1659,3111|mtype=pin|plane=0|mapID=-1}}
}}
```

```
{{Clue info
|id = 973
|text = The cryptic reveals who to speak to:<br><br>Are you somewhat entertained?
|notes = Speak to [[Gloria]] inside the Fortis Colosseum.
|map = {{Map|1802,9504|mtype=pin|plane=0|mapID=-1}}
}}
```

```
{{Clue info
|id = 968
|text = The anagram reveals who to speak to:<br><br>LAME T
|notes = Speak to [[Metla]] at the Stonecutter Outpost.
|map = {{Map|1742,2977|mtype=pin|plane=0|mapID=-1}}
}}
```
