### ISSUE TITLE
Song of the Elves changes

### ISSUE THREAD

**Issue by Alexsuperfly** [runelite/runelite#9459]
### The location of some/all the elves have changed to Prifddinas in post quest state
- [x] Eluned - southwest Prifddinas by the dye trader (hard cipher clue) #10887
- [x] Oronwen still in Lletya (anagram clue)
- [x] Ysgawyn - dead (master anagram clue) - possibly replaced by "RUE GO" anagram
- [ ] Lord Iorwerth - SSW Prifddinas by the teleporter (hard cryptic clue) - apparently this is a different Lord Iorwerth, meaning the clue either hasnt changed or is removed from the possible steps pool since the real Lord Iorwerth perished in the quest
- [x] Bow near lord Iorwerth (master emote clue) changed to "Bow in the Iorwerth Camp." #9471

### New clue steps #9471
- [x] medium anagram "HICK JET" - Jethick in West Ardougne answer: 38 #9455 
- [x] elite cryptic "Has no one told you it is rude to ask a lady her age?" - Lady Tangwen Trahaearn SSE Prifddinas by the teleporter
- [x] master emote "Beckon by a collection of crystalline maple trees. Beware of double agents! Equip Bryophyta's staff and a nature tiara."
- [x] master cryptic "Elvish onions." dig onion patch east of Prifddinas allotment patches
- [x] master anagram "RUE GO" - Goreu in Lletya
- [x] hard cryptic "A general who sets a 'shining' example." Speak to General Hining found at Tyras Camp. #9613
	
### New Timers
- [x] Divine potions #9493
- [x] Zalcano boss #9469 
- [x] Farming patches #9465 
- [x] gauntlet pb tracking #9501
- [x] agility course pb and kc #9492 

### New World map icons #9472 
- [x] SotE quest start
- [x] Rare trees
- [x] Transportation
- [x] agility shortcuts
- [x] update elf camp scroll to Iorwerth camp scroll
- [x] farming patches
- [x] teleport crystal
- [x] minigame

### New overlays
- [x] Prifddinas agility course obstacles #9466 
- [x] Prifddinas mining rocks #9463
- [x] Crystal Implings #9478 

### New loot tracking
- [x] Gauntlet chest #9462 
- [x] Prifddinas crystal chest #9470

### Others
- [x] Prifddinas agility course skill calc addition #9473
- [x] crystal tree skill calc #9473
- [x] Gauntlet consumable information #9461 
- [x] Gauntlet kc tracking #9480 
- [x] Prifddinas and surrounding area skybox #9481 
- [x] Discord area identification #9516
- [x] Add crystal saplings to item identification #9515 
- [x] item stats for divine potions #9576

### Animations for new tools #9511
 - list of discovered animations https://pastebin.com/kYWmPuNB
- [x] idle notifier
- [x] wc plugin
- [x] motherlode plugin
- [x] wintertodt plugin

**Comment by xdesr** [comment]
Prifddinas agility course - skill calc & agility
Zalcano - boss timers
Two allotment patches, crystal tree patch and a flower patch - time-tracking

**Comment by SanderVII** [comment]
Show prifddinas on the world map while not in prifddinas. I know it is that way because of lore, but is is annoying when you try to determine what way to get to the city is best for where you want to be (gauntlet, Zalcano, mines, slayer cave...)

**Comment by nateisonfire** [comment]
Agility overlay (with portal highlighting)

**Comment by SebastiaanVanspauwen** [comment]
New crystal key chest loot tracker support

**Comment by AverageHumanoid** [comment]
New master clue emote step
 ![](https://i.imgur.com/BkoDRMi.png)
and cryptic clue
![](https://i.imgur.com/tlFzuc9.png)

**Comment by Adam-** [comment]
Does the skybox need to be updated for this?

**Comment by AverageHumanoid** [comment]
Elvish onions is for master clue as well

**Comment by Adam-** [comment]
Is there anything else needed on the skill calc? We have just the agility course listed. Divine potions maybe?

**Comment by winterdaze-rs** [comment]
Divine potions give _very_ negligible xp when adding them to the base potion so I'm not sure it should be on the skill calc..adding the dust to a base potion to make a divine potion gives .5 xp per dose

**Comment by ssb-Ranch** [comment]
Just got the elite clue step "Has no one told you it is rude to ask a lady her age?", which Runelite pointed to "Lady Tangwen Trahaearn" but the correct NPC to talk to was Mawrth? Talking to Tangwen did nothing. 

https://oldschool.runescape.wiki/w/Mawrth

**Comment by unseendata** [comment]
> Just got the elite clue step "Has no one told you it is rude to ask a lady her age?", which Runelite pointed to "Lady Tangwen Trahaearn" but the correct NPC to talk to was Mawrth? Talking to Tangwen did nothing.
> 
> https://oldschool.runescape.wiki/w/Mawrth

Also had this issue. I'm guessing the turn in changes with song of the elves completion. So it probably needs to change where it points based on quest completion.

**Comment by Hydrox6** [comment]
It was fixed days ago with https://github.com/runelite/runelite/commit/b87e50e43b9bb4b10342d4ec1a96833e2b9f4109

**Comment by FeelzBradMan** [comment]
Would a Zalcano damage tracker for both shield and mining be useful? To get a pet roll, I think you need to do 50 damage to the shield and 50 mining damage.

**Comment by trelkins3** [comment]
Looks like the Eluned hard cipher clue still hasn't been updated as of 1.6.3, 'near the Prifddinas house portal' might also be good hint text along with the aforementioned 'southwest Prifddinas by the dye trader'.

**Comment by Adam-** [comment]
The problem with this is the hints can't be dynamic:
```java
new CipherClue("OVEXON", "Eluned", new WorldPoint(2289, 3144, 0), "Outside Lletya", "A question on elven crystal math. I have 5 and 3 crystals, large and small respectively. A large crystal is worth 10,000 coins and a small is worth but 1,000. How much are all my crystals worth?", "53,000"),
```
Someone will have to refactor it first to support that.
